"""initial schema

Revision ID: 6c1a91a3737b
Revises: 
Create Date: 2026-04-17 14:29:10.042408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1a91a3737b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('deck_count', sa.Integer(), nullable=False),
    sa.Column('dealer_hits_s17', sa.Boolean(), nullable=False),
    sa.Column('das_allowed', sa.Boolean(), nullable=False),
    sa.Column('surrender', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invite_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('strategy_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('hand_type', sa.String(length=8), nullable=False),
    sa.Column('player_value', sa.String(length=4), nullable=False),
    sa.Column('dealer_upcard', sa.String(length=2), nullable=False),
    sa.Column('correct_action', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_id', 'hand_type', 'player_value', 'dealer_upcard')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ruleset_id', sa.Integer(), nullable=False),
    sa.Column('hand_type', sa.String(length=8), nullable=False),
    sa.Column('player_value', sa.String(length=4), nullable=False),
    sa.Column('dealer_upcard', sa.String(length=2), nullable=False),
    sa.Column('user_action', sa.String(length=4), nullable=False),
    sa.Column('correct_action', sa.String(length=4), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.create_index('ix_user_responses_lookup', ['user_id', 'ruleset_id', 'hand_type', 'player_value', 'dealer_upcard'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_user_responses_lookup')

    op.drop_table('user_responses')
    op.drop_table('strategy_entries')
    op.drop_table('invite_keys')
    op.drop_table('users')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
